import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Box, Typography } from '@mui/material';

const Home: NextPage = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        sx={{
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          height: '100%',
        }}
      >
        <Typography variant="h1">Template</Typography>
      </Box>
    </React.Fragment>
  );
};

export default Home;
